[package]
name = "luajit-src"
version = "210.0.0+694d69a"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]
edition = "2018"
repository = "https://github.com/khvzak/luajit-src-rs"
keywords = ["lua", "luajit"]
readme = "README.md"
license = "MIT"
description = """
Sources of LuaJIT and logic to build it.
"""

[dependencies]
cc = "1.0"
